### ISSUE TITLE
add a license?

### ISSUE THREAD

**Issue by Strryke** [ayush013/folio#21]
Hey ayush, beautiful site. really enjoy the animations, flow, and general aesthetic of your site, esp the timeline!

might wanna add a license, I saw a really similar site that seems *heavily inspired* by yours and I didn't see any crediting: https://github.com/shubh73/devfolio.

**Comment by ayush013** [comment]
Hey, thanks for bringing this up. Looks like someone copied homework without due credits :)
Will add the license and copyright in the coming days.
